name: 3b3tAntiBot
version: ${project.version}
main: me.krymz0n.antibot.Main
authors: [ KRYMZ0N ]
description: An antibot plugin designed for 3b3t, You may use this plugin, however support is limited
website: www.3b3t.me

Commands:
  antibot:
    description: S
